<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1 (Total recall)**

| **Term**   | **Brief description** |
|:--|:--|
| Subsetting |Selecting a subset of ~~a group of elements~~ *the data* in a list or array                       |
| Indexing   |Selecting a single element in a list or array                       |
| Slicing    |Selecting a range of elements in a list or array                       |
| Masking    |Filtering elements in a list or array based on specific conditions                       |

- **Subsetting** can be performed on a **list/array** via **list[]** or **array[]**, where the subset is specified in the **square brackets**
  - **Indexing** a list/array returns a single element from that list/array
    - If the list/array is 1D, the returned element will not be a list, but just that element itself (float, int, str, etc)
    - If the list/array is 2D, the returned element will be a list/array, since each element was already a list/array
  - **Slicing** returns a **list/array** with the specified range of elements
    - Even if we only a single element, it still returns a list/array with that 1 element
  - **Masking** is a special way of subsetting for arrays, by using a **Boolean (True/False) Array** of the same size in the square brackets **[]**, returning an array with only the values that correspond to the **True** indexes in the Boolean Array. The Boolean Array is known as a **Boolean Mask**
    - We can use the Bitwise Operators **~** (NOT), **&** (AND), and **|** (OR) to combine **Boolean Masks**
    - It is possible to subset with an array that is not a Boolean Mask, by using an Index Mask (containing indices to modify the elements on the array)

In [45]:
list = [1,2,3,4,5]
array = np.array(list)
morethan2 = array > 2
lessthan4 = array < 4
morethan2 & lessthan4

array([False, False,  True, False, False])

In [24]:
array1 = np.array([1,2])
array2 = np.array([3,4])
array1 & array2

array([1, 0])

In [46]:
list = [1,2,3,4,5]
array = np.array(list)
type(list[0:1])
list[0:1]

[1]

In [41]:
list = [[0, 0], [1, 1], [2, 2]]
array = np.array(list)
array[0:1]
array[0:1].shape

(1, 2)

In [44]:
list = [1,2,3,4,5]
array = np.array(list)
list3 = [1,2,3]
array3 = np.array(list3)
boolean_array = array3 > 1
boolean_array
array[boolean_array]

IndexError: boolean index did not match indexed array along axis 0; size of axis is 5 but size of corresponding boolean axis is 3

**Exercise 2 (Show me the 'odd' letters)**

In [47]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [48]:
mask_1 = np_array_2d[:, 0]
mask_1

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [49]:
mask_2 = mask_1.astype(int)
mask_2

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [59]:
mask_3 = mask_2%2
mask_3

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [51]:
mask_4 = mask_3 > 0
mask_4

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [52]:
new_array = np_array_2d[mask_4]
new_array

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

In [53]:
print(new_array[:, 1]) # I understand that I could have redefined the same mask at each stage instead of defining new masks
                       # The different masks are simply to visualize what is going on at each stage

['A' 'C' 'E' 'G' 'I']


**Exercise 2 (Show me the 'odd' letters) (After Review)**

My old code for Exercise 2 was messy as I wanted to visualize each step.\
Redoing Exercise 2 in a cleaner format after getting more familiar with Python.

In [5]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [28]:
mask = np_array_2d[:, 0]
mask = mask.astype(int)
mask = mask%2
mask = mask == 1
result = np_array_2d[mask]
print(result[:, 1])

['A' 'C' 'E' 'G' 'I']


The goal of this exercise is to keep performing operations on a copy of the array, until we can ask it a question to obtain a **Boolean Mask**.\
We then use the **Boolean Mask** to subset the original array.

**Exercise 3**

In [73]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [77]:
np_array[np_array < 50] = -1
np_array[np_array > 50] = +1
np_array[np_array == 50] = 0
np_array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])

This shows that asking questions to a 2D array still checks every 2D index in the array.\
Hence, each question asked returns a **2D Boolean Mask** of the same size.\
These 2D Boolean Masks can be used to modify the elements of the original 2D array.\
However, if we were to use the 2D Boolean Mask to Subset the original 2D array, the resultant array will be 1D.

In [75]:
np_array > 50

array([[ True, False,  True, False, False],
       [ True, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [ True, False,  True, False,  True]])

In [76]:
np_array[np_array > 50]

array([66, 57, 92, 88, 75, 76, 51, 87, 71, 67, 69])