<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1 (Total recall)**

| **Term**   | **Brief description** |
|:--|:--|
| Subsetting |Selecting a subset of ~~a group of elements~~ *the data* in a list or array                       |
| Indexing   |Selecting a single element in a list or array                       |
| Slicing    |Selecting a range of elements in a list or array                       |
| Masking    |Filtering elements in a list or array based on specific conditions                       |

**Exercise 2 (Show me the 'odd' letters)**

In [12]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [15]:
mask_1 = np_array_2d[:, 0]
mask_1

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [20]:
mask_2 = mask_1.astype(int)
mask_2

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [24]:
mask_3 = mask_2%2
mask_3

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [25]:
mask_4 = mask_3 > 0
mask_4

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [26]:
new_array = np_array_2d[mask_4]
new_array

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

In [27]:
print(new_array[:, 1]) # I understand that I could have redefined the same mask at each stage instead of defining new masks
                       # The different masks are simply to visualize what is going on at each stage

['A' 'C' 'E' 'G' 'I']


**Exercise 2 (Show me the 'odd' letters) (After Review)**

My old code for Exercise 2 was messy as I wanted to visualize each step.\
Redoing Exercise 2 in a cleaner format after getting more familiar with Python.

In [5]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [28]:
mask = np_array_2d[:, 0]
mask = mask.astype(int)
mask = mask%2
mask = mask == 1
result = np_array_2d[mask]
print(result[:, 1])

['A' 'C' 'E' 'G' 'I']


**Exercise 3**

In [60]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [61]:
np_array[np_array < 50] = -1
np_array[np_array > 50] = +1
np_array[np_array == 50] = 0
np_array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])