<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [2]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

## 1.2 Arrays only | Subsetting by masking

In [4]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [16]:
py_list_2d[3]

[4, 'D']

In [17]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [27]:
py_list_2d[3][0]

4

In [25]:
np_array_2d[3, 0]

np.str_('4')

In [22]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [23]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [29]:
py_list_2d[:3][0]

[1, 'A']

In [30]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [31]:
py_list_2d[3:6][0]

[4, 'D']

In [33]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [34]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [38]:
x = [1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [42]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
x

[1, 2, 3, 4]

In [43]:
x = [1]
x += [2]
x += [3]
x += [4]
x += [5]
x

[1, 2, 3, 4, 5]

In [44]:
x = [1]
x.append(2)
x.append(3)
x.append(4)
x.append(5)
x.append(6)
x

[1, 2, 3, 4, 5, 6]

In [47]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [52]:
x = [1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [51]:
x = [1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [54]:
a = (1, 2, 3)
print(a[0])

1


In [55]:
a[0] = -1

TypeError: 'tuple' object does not support item assignment

In [56]:
a[0] += [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [57]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [63]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Footnotes