<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
import numpy as np

**Python Lists**

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Arrays**

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [6]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

In [11]:
py_super_names[2]    # Forward indexing

'Doctor Strange'

In [9]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [15]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [16]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [18]:
len(py_list_2d)

10

In [19]:
len(np_array_2d)

10

In [21]:
np_array_2d.shape # Gives both the number of elements and dimensions

(10, 2)

## 2.2 Arrays are fussy about type

In [23]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [24]:
py_list

[1, 1.5, 'A']

In [26]:
np_array # Since numpy only supports a single type, it converts the numbers to strings

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [28]:
np_array + 10

array([11, 12, 13, 14, 15])

In [29]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [38]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [39]:
py_list_1 + py_list_2 # Adds the lists by simply merging them into 1 larger list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [40]:
np_array_1 + np_array_2 # Adds the values of the elements with the same index in each array

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [45]:
py_list*2 # Simply doubles the entire list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [46]:
np_array*2 # Multiplies each element in the array by 2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [48]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [50]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [67]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [66]:
py_list == 3 # Meaningless question as we are comparing a whole list to a single number

False

In [54]:
np_array == 3  # Useful as it compares each element in the array to the specified criteria

array([False, False,  True, False, False])

In [55]:
np_array > 3

array([False, False, False,  True,  True])

In [64]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [68]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [69]:
sum(py_list)

15

In [70]:
max(py_list)

5

In [71]:
min(py_list)

1

In [72]:
np_array.sum()

np.int64(15)

In [73]:
np_array.max()

np.int64(5)

In [74]:
np_array.min()

np.int64(1)

In [75]:
np_array.mean()

np.float64(3.0)

In [76]:
np_array.std()

np.float64(1.4142135623730951)

In [77]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

## Footnotes